const QUESTIONS = {
  A: {
    "2": { question: "Un bon echauffement contribue a ?", choices: { a: "Diminuer risques blessure", b: "Augmenter energie ou conscience", c: "Accroitre flexibilite", d: "Toutes ces reponses" } },
    "3": { question: "Technique de respiration recommandee ?", choices: { a: "3 respirations rapides et profondes", b: "Inspirer lentement, retenir 1 sec, expirer lentement", c: "Inspirer profond, retenir longtemps, expirer tranquille", d: "3 respirations lentes, controlees et profondes" } },
    "4": { question: "Les 6 parties du saut en parachutisme ?", choices: { a: "Preparation, sortie, chute libre, CT, controle voilure, pliage", b: "Habillage, briefing, CT, chute libre, voilure, atterrissage", c: "Preparation, equipement, montee, chute libre, voilure, CT", d: "Repetition sol, montee, chute libre, precision, CT, equipement" } },
    "5": { question: "Detenteur brevet A avant progression autonome ?", choices: { a: "Pas responsable progression", b: "Capable planifier seul", c: "Conscient capacites et limites", d: "Peut participer VR4+" } },
    "6": { question: "Premiere etape planification saut ?", choices: { a: "Decider ce que vous allez faire", b: "Mettre combinaison", c: "Mettre equipement", d: "Rassembler equipement" } },
    "7": { question: "Ajuster altimetre si terrain 500 pi plus haut ?", choices: { a: "500 pi plus haut que aeroport", b: "500 pi plus bas que aeroport", c: "Selon altimetre avion", d: "Prevoir tirer 500 pi plus bas" } },
    "8": { question: "Pour procedures urgence, supervision par ?", choices: { a: "Entraineur 1 E1 ou E2", b: "Instructeur largueur IL ou IPAC", c: "Sauteur brevete ou greur", d: "Instructeur classe IC, IL ou E2" } },
    "9": { question: "Difference acceptable entre altimetres en montee ?", choices: { a: "50 pi", b: "100 pi", c: "200 pi", d: "300 pi" } },
    "11": { question: "Acronyme PINT en pliage ?", choices: { a: "Plier, Inspecter, Nommer, Tout demeler", b: "Plier, Inspecter, Nommer, Torsades", c: "Preparer, Inspecter, Nommer, Tout demeler", d: "Preparer, Inspecter, Nommer, Torsades" } },
    "12": { question: "Sequence verification equipement ?", choices: { a: "Haut en bas, gauche droite, avant puis arriere", b: "Bas en haut, gauche droite, avant puis arriere", c: "Haut en bas, droite gauche, arriere puis avant", d: "Bas en haut, droite gauche, arriere puis avant" } },
    "13": { question: "Premier saut voilure plus petite, ouverture a ?", choices: { a: "3500 pi", b: "4000 pi", c: "4500 pi", d: "5000 pi" } },
    "14": { question: "En cas incendie moteur ?", choices: { a: "Ouvrir porte et sortir", b: "Ecouter pilote et attendre instructions", c: "Faire paniquer autres", d: "Trouver extincteur" } },
    "15": { question: "Si parachute sort de avion ?", choices: { a: "Attraper sauteur", b: "Fermer porte", c: "Faire sortir personne", d: "Toutes ces reponses" } },
    "16": { question: "Methode precise determiner derive voilure ?", choices: { a: "Regarder indicateur vent sol", b: "Regarder derive nuages", c: "Lancer indicateur derive vent", d: "Obtenir rapport meteo" } },
    "17": { question: "Sortie urgence avion ?", choices: { a: "Aviser pilote autre passe", b: "Sortie suspendue", c: "Sortie plongee rapide", d: "Confirmer avec pilote" } },
    "18": { question: "Estimer derive chute libre par vent ?", choices: { a: "Virage taux 1 et rapport meteo", b: "Demander pilote et surveiller voilures", c: "Deplacement nuages et derive avion", d: "Anemometre et indicateur derive" } },
    "19": { question: "Verification aiguilles en montee ?", choices: { a: "Eviter frapper rabat reserve", b: "Frapper rabat reserve pour indiquer verification complete" } },
    "20": { question: "Disposition sauteurs dans avion ?", choices: { a: "Couts bas", b: "Faciliter communication", c: "Ordre sortie selon type saut", d: "Vue pour tandems" } },
    "23": { question: "Sortie urgence 1700 pi, utiliser ?", choices: { a: "Parachute principal", b: "Parachute reserve" } },
    "24": { question: "Saut 12500 pi, ouverture 3000 pi, secondes chute libre ?", choices: { a: "46 secondes", b: "50 secondes", c: "55 secondes", d: "65 secondes" } },
    "25": { question: "Methode reduire risque mauvaise perception altitude ?", choices: { a: "Developper notion temps et verifier altimetre", b: "20 sauts par mois", c: "Sauter altitudes differentes", d: "Meme combinaison saut" } },
    "26": { question: "Instable 4000 pi, pas stable 3000 pi, que faire ?", choices: { a: "Ouvrir immediatement", b: "Revenir stable, lancer 2500 pi stable ou non", c: "Retablir stable puis lancer", d: "Tirer reserve" } },
    "27": { question: "Difficulte sortir extracteur 3500 pi ?", choices: { a: "Tirer reserve immediatement", b: "Essayer jusqu 2200 pi puis reserve", c: "Essayer encore, sinon reserve", d: "Attendre activation DDA" } },
    "28": { question: "Evaluer situation, toujours garder esprit ?", choices: { a: "Altitude plancher", b: "Visuel aire atterrissage", c: "Partenaires saut visibles", d: "Urgences anterieures" } },
    "29": { question: "Controler taux chute VR ?", choices: { a: "Plier ou allonger jambes", b: "Position bras haut ou bas", c: "Position symetrique boite et cambrure", d: "Combiner bras et jambes" } },
    "30": { question: "Procedure arret manoeuvres separation horizontale VR ?", choices: { a: "Signaler, 180, driver 3-5 sec, retablir, localiser trafic, agiter bras, lancer, preparer elevateurs", b: "Signaler, 180, driver 5-7 sec, retablir, agiter, lancer, elevateurs", c: "Signaler, retourner, separer, lancer", d: "Signaler, retourner, lancer" } },
    "31": { question: "Detenteur brevet A ne devrait pas sauter sans casque protecteur ?", choices: { a: "Vrai", b: "Faux" } },
    "32": { question: "Freins appliques, cellules extremes se touchent, manoeuvre ?", choices: { a: "Evitement turbulence", b: "Arrondi", c: "Evitement urgence", d: "Decrochage" } },
    "33": { question: "Elements decision reduire taille voilure ?", choices: { a: "Limites fabricant etiquette", b: "Tableau reduction", c: "Exercer habiletes au-dessus 2000 pi", d: "Toutes ces reponses" } },
    "34": { question: "Recuperer decrochage atterrissage ?", choices: { a: "Remonter poignees legerement pour freiner", b: "Pomper poignees et atterrir", c: "Retour vol plan graduel", d: "Descendre poignees plus bas taille" } },
    "35": { question: "Voilures volent lune vers autre, que faire ?", choices: { a: "Prendre poignees et virer eviter collision", b: "Virage droite elevateurs arriere", c: "Tirer gauche rapidement, laisser droite", d: "Crier autre sauteur" } },
    "36": { question: "Regle priorite sous voilure ?", choices: { a: "Solos priorite tandems", b: "Solos priorite cameramans", c: "Reserves priorite principales", d: "Experimentes priorite eleves" } },
    "37": { question: "Mauvais fonctionnement voilure, reaction ?", choices: { a: "REGARDER, PRENDRE, TIRER, EVALUER", b: "EVALUER, REFLECHIR, REAGIR", c: "IDENTIFIER, EVALUER, REPONDRE", d: "JETER COUP OEIL, TIRER, PRIER" } },
    "38": { question: "Turbulence approche atterrissage ?", choices: { a: "Poignees haut, pleine vitesse", b: "Diriger elevateurs avant, freiner avec avant", c: "Freins 50, atterrir elevateurs arriere", d: "Freiner fond jusqu atterrissage" } },
    "39": { question: "Manoeuvres evitement voilure ?", choices: { a: "Mains haut, attendre gonflage complet, elevateur arriere, 90", b: "Mains haut, pendant gonflage, elevateur arriere, 180", c: "Mains haut, attendre gonflage complet, elevateur arriere, 180", d: "Mains haut, pendant gonflage, elevateur arriere, 90" } },
    "40": { question: "Collision sous voilure ?", choices: { a: "Plus bas priorite", b: "Freiner 50 tenir jusqu degage", c: "Coups pieds sortir", d: "Contact corps a corps" } },
    "41": { question: "Pique elevateurs avant, voilure ?", choices: { a: "Augmentera vitesse et taux descente", b: "Diminuera", c: "Maintiendra", d: "Toutes reponses" } },
    "42": { question: "Avec qui NE PAS participer VR2 ?", choices: { a: "Detenteur certificat solo", b: "Brevet A avec annotation VR groupe", c: "Detenteur brevet B", d: "Detenteur brevet C" } },
    "43": { question: "Altitude minimale activation principal brevet A ?", choices: { a: "2000 pi", b: "2500 pi", c: "3000 pi", d: "2800 pi" } },
    "44": { question: "Cloture obstacle si plus de combien metres ?", choices: { a: "2,5 m", b: "3 m", c: "3,5 m", d: "4 m" } },
    "45": { question: "Distance minimale obstacle-cible brevet A ?", choices: { a: "25 m", b: "150 m", c: "100 m", d: "200 m" } },
    "46": { question: "Vitesse vent surface max brevet A ?", choices: { a: "5 m/sec", b: "9 m/sec", c: "11 m/sec", d: "7 m/sec" } },
    "47": { question: "Extracteur-drisse pris dans main, essayer liberer jusqu reussite ?", choices: { v: "Vrai", f: "Faux" } },
    "48": { question: "Reserves inspectees et repliees tous 180 jours ?", choices: { v: "Vrai", f: "Faux" } },
    "49": { question: "Remonter poignees trop vite, voilure bondira, risque blessure ?", choices: { v: "Vrai", f: "Faux" } },
    "50": { question: "Brevet A peut sauts de nuit ?", choices: { v: "Vrai", f: "Faux" } },
    "51": { question: "Brevet A peut FSV si competent voilure dynamique ?", choices: { v: "Vrai", f: "Faux" } },
    "52": { question: "Virage plat doit etre enseigne ?", choices: { v: "Vrai", f: "Faux" } },
    "53": { question: "Sauts conformes Reglement aviation canadien ?", choices: { a: "RGS", b: "Recommandation" } },
    "54": { question: "VR4 necessite brevet B ou plus ?", choices: { a: "RGS", b: "Recommandation" } },
    "55": { question: "Sauts camera necessitent brevet B minimum ?", choices: { a: "RGS", b: "Recommandation" } },
    "56": { question: "Personne doit posseder formation et qualifications requises ?", choices: { a: "RGS", b: "Recommandation" } },
    "57": { question: "Eleve ou solo doit DDA fonctionnel jusqu brevet A ?", choices: { a: "RGS", b: "Recommandation" } },
    "58": { question: "Premier saut nuit devrait etre supervise ?", choices: { a: "RGS", b: "Recommandation" } },
    "59": { question: "Interdit sauter sous influence drogues, alcool ?", choices: { a: "RGS", b: "Recommandation" } },
  },
  B: {
    "2": { question: "Techniques eviter blocage mental ?", choices: { a: "Vue ensemble", b: "Rechercher rythme sequence", c: "Pratique mentale montee", d: "Toutes ces reponses" } },
    "3": { question: "3 occasions pratique mentale ?", choices: { a: "Apres repetition sol, habillage, montee", b: "Avant repetition sol, montee, sortie", c: "Sortie, avant points, separation", d: "Repetition sol, chute libre, ouverture" } },
    "4": { question: "C.A.S.S. veut dire ?", choices: { a: "Casse-tetes", b: "Angles", c: "Signaux", d: "Secrets" } },
    "5": { question: "Repetition sol importante faite comment ?", choices: { a: "Ressembler saut veritable", b: "Avec gens experimentes", c: "Vitesse plus lent", d: "Sur planche roulettes" } },
    "6": { question: "Controler stress ?", choices: { a: "Relaxation", b: "Stimulation", c: "Preparation mentale concentration", d: "Toutes ces reponses" } },
    "7": { question: "S.M.A.R.T. veut dire ?", choices: { a: "Specifique", b: "Mesurable", c: "Atteignable", d: "Realiste" } },
    "8": { question: "Tissu plus traine au moins traine ?", choices: { a: "Coton, poly-coton, nylon, spandex", b: "Poly-coton, coton, nylon, spandex", c: "Coton, poly-coton, spandex, nylon", d: "Coton, spandex, poly-coton, nylon" } },
    "9": { question: "Ralentir vitesse ouverture chocs violents ?", choices: { a: "Glisseur plus petit", b: "Raccourcir elastiques", c: "Contacter fabricant voilure", d: "Extracteur Zero-P plus petit" } },
    "11": { question: "Charge trop legere ou lourde nuit performance ?", choices: { v: "Vrai", f: "Faux" } },
    "12": { question: "Allongement ratio est portance vs traine ?", choices: { v: "Vrai", f: "Faux" } },
    "13": { question: "Vitesse avant voilures entre 20 et 38 mi/h ?", choices: { v: "Vrai", f: "Faux" } },
    "14": { question: "Jamais utiliser voilure excede capacites ?", choices: { v: "Vrai", f: "Faux" } },
    "15": { question: "Virage taux 1 ?", choices: { a: "360 avion 2 min, derive vent altitude", b: "360 voilure arrets 90, direction vent", c: "360 chute libre debut fin point fixe", d: "2 min avion avertir equipe sol etudiants" } },
    "16": { question: "Virage taux 1, point depart fin different, calculer sortie ?", choices: { a: "Compenser distance, ajouter passe largage", b: "Compenser distance, soustraire passe largage", c: "Compenser moitie distance", d: "Aucun ajustement" } },
    "17": { question: "Connaissance instruments bord ?", choices: { a: "Non necessaire", b: "Pratique determiner situation avion", c: "Necessaire urgence", d: "Au-dela objectifs parachutisme" } },
    "18": { question: "2400 pi urgence pilote SORTEZ, action ?", choices: { a: "Sortie plongee, ouvrir reserve", b: "Sortie plongee, ouvrir principal", c: "Ceinture, atterrissage urgence", d: "Demander aide pilote" } },
    "19": { question: "Prerequis freefly ?", choices: { a: "Formation sol freefly", b: "100 sauts minimum", c: "Controle saltos avant arriere tonneaux", d: "Position debout 10 secondes" } },
    "20": { question: "Equipe 4 sous altitude separation 4500 pi ?", choices: { a: "Ouvrir immediatement", b: "180 centre, driver, deployer, elevateurs arriere, evitement", c: "Separation normale, ouvrir avant ralenti", d: "Activer reserve" } },
    "23": { question: "Quelqu'un vole dessous vous altitude ouverture ?", choices: { a: "Ouvrir immediatement", b: "Vous eloigner", c: "Agiter bras", d: "Rester au-dessus haut" } },
    "24": { question: "Transition assise freefly instable, que faire ?", choices: { a: "Signaler, ouvrir, verifier", b: "Position ventre ouvrir altitude prevue", c: "Rouler ventre, altimetre, attendre ouverture", d: "Sur dos, relaxer, altimetre, recommencer" } },
    "25": { question: "En freefly, corking signifie ?", choices: { a: "Ouvrir bouteille chute libre", b: "VR vertical 4", c: "Passer debout ou tete bas a ventre terre", d: "Drive tete bas" } },
    "26": { question: "Consideration securite vol tete bas groupe ?", choices: { a: "Difficile voir tout monde", b: "Vitesse rapprochement augmente", c: "Difficile rappeler formations", d: "Sorties difficiles" } },
    "27": { question: "Virage zig zag Sashay FSV ?", choices: { a: "Perdre altitude rapide", b: "Abaisser manettes sans virage", c: "FSV seulement", d: "Accelerer mouvement avant sans sacrifier altitude" } },
    "28": { question: "Saut precision, angle approche se nomme ?", choices: { a: "Angle approche", b: "Angle descente", c: "Ligne approche", d: "Point largage designe" } },
    "29": { question: "Situations inhabituelles FSV, 2 categories ?", choices: { a: "Problemes et procedures", b: "Biplans et downplanes", c: "Emmelements et enroulements", d: "Haute vitesse basse vitesse" } },
    "30": { question: "Type virage cause plus perte altitude ?", choices: { a: "Virage plat", b: "Virage elevateurs avant", c: "Virage elevateur arriere", d: "Virage plein vol plan" } },
    "31": { question: "Voilures visent charge specifique appelee ?", choices: { a: "Capacite aile", b: "Tolerance aile", c: "Surface aile", d: "Charge alaire" } },
    "37": { question: "Vitesse max vent sol brevet B ?", choices: { a: "5 m/sec", b: "7 m/sec", c: "9 m/sec", d: "11,2 m/sec" } },
    "38": { question: "Vitesse max vent saut nuit ou eau ?", choices: { a: "5 m/sec", b: "7 m/sec", c: "9 m/sec", d: "11,2 m/sec" } },
    "39": { question: "Distance minimale obstacle brevet B ?", choices: { a: "150 m", b: "100 m", c: "200 m", d: "300 m" } },
    "41": { question: "Liberation intentionnelle necessite brevet ?", choices: { a: "Solo", b: "A", c: "B", d: "C" } },
    "47": { question: "200 sauts, formation wingsuit parachutiste experimente ?", choices: { v: "Vrai", f: "Faux" } },
    "53": { question: "Sortie drive flottante, tenir position jusqu rattraper vitesse avion ?", choices: { v: "Vrai", f: "Faux" } },
    "54": { question: "Hypoxie diminution oxygenation arterielle ?", choices: { v: "Vrai", f: "Faux" } },
    "55": { question: "Reperage vent arriere par rapport vents sol ?", choices: { v: "Vrai", f: "Faux" } },
    "56": { question: "Incident haute vitesse traiter comme blessure cou ?", choices: { v: "Vrai", f: "Faux" } },
    "57": { question: "2 min avant sortie, repetition mentale ?", choices: { v: "Vrai", f: "Faux" } },
    "58": { question: "Parachutistes solo quittent avant tandem ?", choices: { v: "Vrai", f: "Faux" } },
    "59": { question: "Capacites jusqu 18000 pi 20-30 min ?", choices: { v: "Vrai", f: "Faux" } },
  },
  C: {
    "2": { question: "Planification VR, facteurs importants ?", choices: { a: "Regles competition, formations hasard, blocs", b: "Aide entraineur 2", c: "Nombre sauteurs, manoeuvres, types figures", d: "Etapes grille habiletes" } },
    "3": { question: "Repetition sol optimale quand ?", choices: { a: "VR4 seulement", b: "CASS : Casse-tetes, Angles, Signaux, Secrets", c: "Pres avion avant embarquement", d: "Contact visuel centre formation" } },
    "4": { question: "Pourquoi fixer objectifs ?", choices: { a: "Devenir competitif rapide", b: "Direction, interet, motivation, satisfaction", c: "Reduire nombre sauts tache", d: "Motivation rester sport" } },
    "5": { question: "Sortie pique-delta utilisee ?", choices: { a: "Freestyle", b: "Vitesse sortie rapide, controle VR", c: "Rattraper ecart vertical base VR", d: "Diminuer vent relatif sortie" } },
    "6": { question: "Sortie drive flottante floater track ?", choices: { a: "Diminuer vent relatif", b: "Grandes formations gros porteurs", c: "Surface maximale, diminuer taux descente", d: "Quitter tot, distance horizontale verticale" } },
    "7": { question: "Ordre sortie valable ?", choices: { a: "VR grandes puis petites, freefly grandes puis petites, PAC, tandems, wingsuit, ouverture haute", b: "VR grandes puis petites, freefly grandes puis petites, tandems, PAC, wingsuit, ouverture haute", c: "Freefly grandes puis petites, VR grandes puis petites, PAC, tandems, wingsuit, ouverture haute", d: "Freefly grandes puis petites, VR grandes puis petites, wingsuit, PAC, tandems, ouverture haute" } },
    "8": { question: "Avantage sortie sans prise VR4 apprentissage ?", choices: { a: "Prevenir sortie instable", b: "Garder sauteurs proches", c: "Preparer accrocher avion", d: "Maitriser vol minimum tension depart" } },
    "9": { question: "Sortie prise destabilise, que faire ?", choices: { a: "Lacher, arquer, reconstruire", b: "Tenir formation, arquer", c: "Pousser centre, resserrer", d: "Changer prise, surface base adequate" } },
    "11": { question: "Transition position assise efficace ?", choices: { a: "Menton releve, poitrine ouverte, pousser talons", b: "Ventre terre, pousser pieds dessous", c: "Ventre terre, stag, pousser autre jambe", d: "Salto arriere, ouvrir avant fin" } },
    "12": { question: "VR, compagnon secoue bras 8000 pi, que faire ?", choices: { a: "Point suivant", b: "Refaire dernier point", c: "Anormal, lacher prise", d: "Garder prise aider" } },
    "13": { question: "9000 pi, tombez 20 pi plus bas, glissez dessous ?", choices: { a: "Ralentir remonter immediat", b: "Driver jusqu 3500, signal, tirer", c: "Cote, ralentir plus haut, approcher nouveau", d: "Cote, ralentir, approcher niveau bas" } },
    "14": { question: "3 conditions reussir VR ?", choices: { a: "Position neutre, virages axe central, appontages doux", b: "Sortie stable, taux descente controle, appontages doux", c: "Position porte, angles, figures", d: "Niveau, proximite, synchronisation" } },
    "15": { question: "Virage sous voilure, que faire ?", choices: { a: "Regarder droit devant", b: "Regarder direction virage verifier trafic", c: "Regarder au-dessus derriere", d: "Indiquer direction bras tendu" } },
    "16": { question: "Approche finale, pres derriere plus haut autre voilure ?", choices: { a: "Crier ceder passage", b: "Deplacer cote ne plus etre derriere", c: "180 hook turn, atterrir ailleurs", d: "Freiner moitie, separation horizontale" } },
    "17": { question: "Vitesse max vents surface brevet C ?", choices: { a: "5 m/sec", b: "7 m/sec", c: "9 m/sec", d: "11,2 m/sec" } },
    "18": { question: "FSV participants 100 sauts voilure rectangulaire ?", choices: { v: "Vrai", f: "Faux" } },
    "19": { question: "FSV approche appontage au-dessus 2000 pi ?", choices: { v: "Vrai", f: "Faux" } },
    "20": { question: "FSV altitude min separation 1000 pi ?", choices: { v: "Vrai", f: "Faux" } },
    "23": { question: "Atterrissage eau, procedure ?", choices: { a: "Gonfler flottaison, detacher poitrine, cuissarde, sortir, ramasser, bateau", b: "Poitrine, gonfler, desserrer cuissardes, liberer voilure au-dessus eau, bateau", c: "Poitrine, gonfler, cuissardes apres eau, sortir, ramasser, nager", d: "Poitrine, gonfler, cuissardes, amerrir vent, sortir, ramasser, bateau" } },
    "24": { question: "Combinaison ajustee jambes ample bras pour ?", choices: { a: "Voltige precision", b: "FSV", c: "Competition VR", d: "Freestyle" } },
    "25": { question: "Fonction couvre-chaussures booties ?", choices: { a: "Protection brulures suspentes FSV", b: "Faciliter virages, vitesse drive", c: "Inclinaison avant compenser glissade", d: "Jambes tendues, surface lisse eviter accrochage" } },
    "26": { question: "Pourquoi porter poids supplementaire ?", choices: { a: "Limiter plage controle", b: "Corriger ameliorer position", c: "Sauteurs legers meme niveau autres", d: "Mode, mieux corriger position" } },
    "27": { question: "Se familiariser pliage nouvelle voilure ?", choices: { a: "Catalogue equipement", b: "Manuel utilisateur fabricant", c: "Technique derniere voilure", d: "Demander copain" } },
    "28": { question: "Voilure rectangulaire plus stable ?", choices: { a: "Grande surface, allongement eleve", b: "Grande surface, faible allongement", c: "Petite surface, allongement eleve", d: "Petite surface, faible allongement" } },
    "29": { question: "3 accessoires saut nuit : 1.Altimetre lumineux 2.Lampe casque 360 3.Altimetre sonore 4.Lampe poche ?", choices: { a: "1, 2, 3", b: "2, 3, 4", c: "3, 4, 1", d: "4, 1, 2" } },
    "30": { question: "Systeme flottaison sauts eau ?", choices: { a: "CO2 seulement", b: "Bouche seulement", c: "CO2 et bouche", d: "Couleur vive" } },
    "31": { question: "Brevet C contresigner toutes annotations ?", choices: { v: "Vrai", f: "Faux" } },
    "32": { question: "Brevet C atterrir terrain 50 m degagement ?", choices: { v: "Vrai", f: "Faux" } },
    "33": { question: "Brevet C VR nuit avec experience saut nuit ?", choices: { v: "Vrai", f: "Faux" } },
    "34": { question: "Brevet C admissible cours instructeur PAC ?", choices: { v: "Vrai", f: "Faux" } },
    "35": { question: "Brevet C fabriquer indicateurs derive vent ?", choices: { v: "Vrai", f: "Faux" } },
    "36": { question: "Brevet C inspecter replier reserves ?", choices: { v: "Vrai", f: "Faux" } },
    "37": { question: "Brevet C demande certificat saut demonstration CSD ?", choices: { v: "Vrai", f: "Faux" } },
    "38": { question: "Brevet C admissible cours entraineur 2 si E1 ?", choices: { v: "Vrai", f: "Faux" } },
    "39": { question: "Brevet C deroger RGS ou modifier ?", choices: { v: "Vrai", f: "Faux" } },
    "40": { question: "Brevet C fonction responsable securite centre ?", choices: { v: "Vrai", f: "Faux" } },
    "41": { question: "Brevet C controleur sol sauts demonstration ?", choices: { v: "Vrai", f: "Faux" } },
    "42": { question: "30 min vol 10000-13000 pi ANM sans oxygene interdit ?", choices: { v: "Vrai", f: "Faux" } },
    "43": { question: "Au-dessus 20000 pi ANM masque oxygene necessaire ?", choices: { v: "Vrai", f: "Faux" } },
    "44": { question: "Equipement different, qui fournit indications ?", choices: { a: "Brevet C", b: "Entraineur 1", c: "Juge provincial", d: "Entraineur 2" } },
    "45": { question: "2 voilures meme modele tailles differentes meme charge alaire, meme performance ?", choices: { a: "Oui, taille importe pas", b: "Non, depend habiletes", c: "Non, tailles differentes pas meme performance", d: "Oui si carrees semi-elliptiques" } },
    "46": { question: "Altitude hypoxie affecte vision nuit ?", choices: { a: "Au-dessus 5000 pi", b: "Chute libre seulement", c: "Au-dessus 12000 pi", d: "Jamais" } },
    "47": { question: "Flotteur en VR ?", choices: { a: "Taux descente faible", b: "Part avant base, drive delta remonter", c: "Flotte exterieur avion attend autres", d: "Arc inverse remonter si passe dessous" } },
    "48": { question: "Pourquoi saut voltige serie croisee chronometre brevet C ?", choices: { a: "Progression normale avant VR", b: "Habiletes plusieurs disciplines", c: "Demontrer controle vigilance", d: "Requis assurance ACPS" } },
    "49": { question: "DDA tombe eau, que faire ?", choices: { a: "Rien", b: "Secher immediat", c: "Replier reserve", d: "Consulter greur" } },
    "50": { question: "Inspection systeme 3 anneaux, elements examiner ?", choices: { a: "Assemblage, rotation anneaux, flexibilite sangles", b: "Etat boucle, sangles, assemblage anneaux", c: "Etat sangles, taille, acheminement ouverture auto", d: "Flexibilite sangles, etat anneaux, rotation" } }
  }
};

module.exports = { QUESTIONS };
